# Generated by Django 2.1.2 on 2018-10-15 08:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Japan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jcode', models.CharField(help_text='5 桁の JIS コード', max_length=5, verbose_name='市区町村コード')),
                ('ken', models.CharField(help_text='', max_length=10, verbose_name='都道府県名')),
                ('sicho', models.CharField(blank=True, help_text='', max_length=20, verbose_name='支庁名・振興局名')),
                ('gun', models.CharField(blank=True, help_text='', max_length=20, verbose_name='郡名（町村部のみ）')),
                ('seirei', models.CharField(blank=True, help_text='', max_length=20, verbose_name='政令指定都市の市名')),
                ('sikuchoson', models.CharField(blank=True, help_text='政令指定都市の場合は区名', max_length=50, verbose_name='市区町村名')),
                ('city_eng', models.CharField(help_text='', max_length=50, verbose_name='市区町村名（英語）')),
                ('p_num', models.IntegerField(help_text='「住民基本台帳に基づく人口、人口動態及び世帯数（平成 28 年 1 月 1 日現在） 総務省」による', null=True, verbose_name='人口')),
                ('h_num', models.IntegerField(help_text='「住民基本台帳に基づく人口、人口動態及び世帯数（平成 28 年 1 月 1 日現在） 総務省」による', null=True, verbose_name='世帯数')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='content - points フィールドの geojson - Point 表現', srid=4612)),
            ],
        ),
        migrations.AddIndex(
            model_name='japan',
            index=models.Index(fields=['jcode'], name='geo_japan_j_jcode_6ff340_idx'),
        ),
    ]
